version: '2'
services:
  # --------------------------------------------------------------------------
  # Caddy
  # --------------------------------------------------------------------------
  caddy:
    image: abiosoft/caddy:latest
    restart: unless-stopped
    hostname: caddy
    env_file: .env
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile
      - ./staticfiles:/var/www/chagrade/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    links:
      - django
    logging:
      options:
        max-size: "200k"
    container_name: caddy
  # --------------------------------------------------------------------------
  # Django/Gunicorn
  # --------------------------------------------------------------------------
  django:
    build: .
    restart: unless-stopped
    hostname: django
    command: /usr/local/bin/gunicorn chagrade.wsgi:application -w 2 -b :8000 --reload
    env_file: .env
    volumes:
      - .:/app
#    ports:
#      - "8000:8000"
    depends_on:
      - postgres
    links:
      - postgres
    logging:
      options:
        max-size: "200k"
    container_name: django
    stdin_open: true
    tty: true
  # --------------------------------------------------------------------------
  # Database
  # --------------------------------------------------------------------------
  postgres:
    image: postgres:9.5
    restart: unless-stopped
    environment:
      - PGDATA=/app/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./var/lib/postgresql/data:/app/var/lib/postgresql/data
    env_file: .env
    logging:
      options:
        max-size: "200k"
    container_name: postgres
  #-----------------------------------------------
  #   Rabbitmq Service
  #-----------------------------------------------
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    container_name: rabbit
    hostname: rabbit
    env_file: .env
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./var/rabbitmq:/var/lib/rabbitmq/
  #-----------------------------------------------
  #   Celery Service
  #-----------------------------------------------
  celery:
    container_name: celery
    restart: unless-stopped
    hostname: celery
    command: bash -c "celery -A chagrade worker --loglevel=debug"
    working_dir: /app/
    build:
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - DJANGO_SETTINGS_MODULE=chagrade.settings.base
    env_file: .env
    volumes:
      - .:/app
  #-----------------------------------------------
  #   Flower Service
  #-----------------------------------------------
  flower:
    container_name: flower
    restart: unless-stopped
    hostname: flower
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.flower
    ports:
      - 15555:5555
    depends_on:
      - celery
      - rabbitmq
