version: 2
jobs:
  build:
    environment:
      DJANGO_SETTINGS_MODULE: chagrade.settings.base
      DB_NAME: chagrade_website
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost
      POSTGRES_DB: chagrade_website
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    docker:
      - image: circleci/python:3.6
      - image: postgres:9.5
    steps:
      - checkout
      - run:
          name: Set ENV Vars
          command: export DJANGO_SETTINGS_MODULE="chagrade.settings.base"
      - run:
          name: CHOWN Python Library Dirs
          command: sudo chown -R $(whoami) /usr/local/
      - run:
          name: PIP Install Requirements
          command: pip install -r requirements.txt
      - run:
          name: Collect Static
          command: python manage.py collectstatic
      - run:
          name: Run PyTest
          command: py.test
